import React,{useEffect,useState} from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter,Routes,Route } from 'react-router-dom';
import './style.css';
const blank={title:'New search',mode:'jobs',companies:[],roles:[],skills:[],locations:[],strictCompany:false,strictRole:false,strictSkills:false,resume:'',prompt:'',limit:10,enabled:true};
const TAB_KEY='djs.tabs',REPORT_KEY='djs.reports';
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))||fallback;}catch{return fallback;}}
async function api(path,method='GET',body){const r=await fetch('/api'+path,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});if(!r.ok){const e=await r.json();throw new Error(e.details?.map(x=>x.message).join('; ')||e.error||'Request failed');}return r.status===204?null:r.json();}
function App(){
 const [tabs,setTabs]=useState(()=>read(TAB_KEY,[])),[active,setActive]=useState(()=>read(TAB_KEY,[])[0]?.code),[form,setForm]=useState(blank),[reports,setReports]=useState([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[usage,setUsage]=useState(0),[prune,setPrune]=useState(false),[restore,setRestore]=useState('');
 const [saved,setSaved]=useState(()=>read(REPORT_KEY,[]));
 function store(key,value){try{localStorage.setItem(key,JSON.stringify(value));updateUsage();return true;}catch{setNotice('Browser storage is full or unavailable. Export reports before removing old ones.');return false;}}
 function updateUsage(){let bytes=0;for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);bytes+=(k.length+(localStorage.getItem(k)||'').length)*2;}setUsage(bytes);}
 useEffect(()=>{store(TAB_KEY,tabs);},[tabs]);
 useEffect(()=>{updateUsage();},[]);
 useEffect(()=>{let current=true;setNotice('');setReports([]);const tab=tabs.find(t=>t.code===active);setForm(tab?.config||blank);if(active)api(`/searches/${active}/reports`).then(r=>{if(current)setReports(r);}).catch(e=>{if(current)setNotice(e.message);});return()=>{current=false;};},[active]);
 const change=(key,value)=>setForm(f=>({...f,[key]:value}));
 async function action(fn){setBusy(true);setNotice('');try{await fn();}catch(e){setNotice(e.message);}finally{setBusy(false);}}
 async function save(){const clean={...form,...Object.fromEntries(['companies','roles','skills','locations'].map(k=>[k,form[k].filter(x=>x.trim())]))};if(active){await api(`/searches/${active}`,'PUT',clean);setTabs(ts=>ts.map(t=>t.code===active?{...t,config:clean}:t));return active;}const t=await api('/searches','POST',clean);setTabs(ts=>[...ts,t]);setActive(t.code);return t.code;}
 function exportReports(){const url=URL.createObjectURL(new Blob([JSON.stringify(saved,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='job-search-reports.json';a.click();URL.revokeObjectURL(url);}
 return <div className="min-h-screen bg-slate-950 text-slate-100 pb-28"><header className="border-b border-slate-800"><div className="max-w-6xl mx-auto px-6 py-5 flex flex-wrap gap-4 items-center justify-between"><div><p className="text-teal-300 text-xs uppercase tracking-widest">Your next opportunity</p><h1 className="text-xl font-semibold">Daily Job Search Report</h1></div><div className="text-sm text-slate-400">Browser storage: {(usage/1024).toFixed(1)} KB <button onClick={()=>setPrune(true)}>Delete reports 30+ days old</button><button disabled={!saved.length} onClick={exportReports}>Export saved reports</button></div></div></header>
 <main className="max-w-6xl mx-auto p-6"><div className="flex gap-3 mb-6"><input aria-label="Restore search code" placeholder="Restore a tab with its search code" value={restore} onChange={e=>setRestore(e.target.value)}/><button disabled={busy||!restore} onClick={()=>action(async()=>{const t=await api(`/searches/${restore.trim()}`);setTabs(ts=>ts.some(x=>x.code===t.code)?ts:[...ts,t]);setActive(t.code);setRestore('');})}>Restore tab</button></div>
 {notice&&<p role="status" className="bg-amber-950 text-amber-100 p-4 rounded mb-5">{notice}</p>}
 <section className="panel"><div className="flex justify-between flex-wrap gap-3"><div><h2 className="text-2xl font-semibold">Shape your search</h2><p className="text-slate-400 mt-1">Save your criteria. Get a daily report, or search when you’re ready.</p></div><button disabled={busy} onClick={()=>action(async()=>{const code=await save();await api(`/searches/${code}/run`,'POST');setReports(await api(`/searches/${code}/reports`));setNotice('Search complete.');})}>{busy?'Working…':'Run search now'}</button></div>
 <fieldset disabled={busy} className="mt-6"><div className="grid md:grid-cols-2 gap-5"><label>Tab title<input value={form.title} onChange={e=>change('title',e.target.value)}/></label><div><span className="label">Search mode</span><div className="flex gap-6 py-3">{['jobs','news'].map(mode=><label key={mode} className="flex gap-2 items-center"><input type="radio" name="mode" checked={form.mode===mode} onChange={()=>change('mode',mode)}/>{mode==='jobs'?'Jobs':'Tech news'}</label>)}</div></div></div>
 {form.mode==='jobs'?<><div className="grid md:grid-cols-2 gap-5 mt-5">{[['companies','Companies'],['roles','Job titles'],['skills','Key skills'],['locations','Locations']].map(([key,label])=><label key={key}>{label}<input value={form[key].join(',')} placeholder="Separate entries with commas" onChange={e=>change(key,e.target.value.split(',').map(x=>x.trim()))}/></label>)}</div><div className="flex flex-wrap gap-6 my-5">{[['strictCompany','Require a listed company'],['strictRole','Require a listed title'],['strictSkills','Require all listed skills']].map(([key,label])=><label key={key} className="flex gap-2 items-center"><input type="checkbox" checked={form[key]} onChange={e=>change(key,e.target.checked)}/>{label}</label>)}</div><label>Resume text<textarea rows="6" value={form.resume} onChange={e=>change('resume',e.target.value)} placeholder="Paste your resume for fit scores and ATS keyword suggestions"/></label><p className="text-xs text-slate-400 mt-2">Your resume is stored in this browser and the backend, and sent to OpenAI for evaluation. Keep your search code private.</p></>:<label className="block mt-5">News search prompt<textarea rows="4" value={form.prompt} onChange={e=>change('prompt',e.target.value)} placeholder="New technologies for software developers, or industry trends…"/></label>}
 <div className="flex flex-wrap gap-6 items-end mt-5"><label>Results to search (1–20)<input type="number" min="1" max="20" value={form.limit} onChange={e=>change('limit',Number(e.target.value))}/></label><label className="flex gap-2 items-center py-3"><input type="checkbox" checked={form.enabled} onChange={e=>change('enabled',e.target.checked)}/>Run daily at 2 a.m. server timezone</label><button onClick={()=>action(async()=>{await save();setNotice('Search settings saved.');})}>Save settings</button></div><p className="text-xs text-slate-400 mt-3">Strict filters and duplicate removal may return fewer results than requested.</p>
 </fieldset>{active&&<div className="mt-6 border-t border-slate-700 pt-4"><span className="text-sm text-slate-400">Search ID key </span><code className="text-sm break-all">{active}</code><button onClick={()=>navigator.clipboard.writeText(active).then(()=>setNotice('Search code copied.')).catch(()=>setNotice('Select and copy the code above.'))}>Copy</button><button disabled={busy} onClick={()=>action(async()=>{await api(`/searches/${active}`,'DELETE');const remaining=tabs.filter(t=>t.code!==active);setTabs(remaining);setActive(remaining[0]?.code);})}>Delete search</button></div>}</section>
 <section className="mt-8"><div className="flex justify-between items-center mb-4"><h2 className="text-xl font-semibold">Your reports</h2><button disabled={busy||!active} onClick={()=>action(async()=>setReports(await api(`/searches/${active}/reports`)))}>Refresh reports</button></div>{!reports.length&&<div className="panel text-slate-400">Your reports will appear here after a search runs.</div>}{reports.map(report=><article className="panel mb-4" key={report.id}><div className="flex justify-between flex-wrap gap-3 mb-4"><div><h3 className="font-semibold">{new Date(report.created_at||Date.now()).toLocaleString()}</h3><p className="text-sm text-slate-400">{report.source} · {report.status} · {report.results.length} results</p></div><button disabled={report.status!=='completed'} onClick={()=>{const next=[...saved.filter(r=>r.id!==report.id),{...report,tabTitle:form.title}];if(store(REPORT_KEY,next)){setSaved(next);setNotice('Report saved in this browser.');}}}>Save report locally</button></div>{report.error&&<p className="text-amber-200">{report.error}</p>}{report.warnings?.map((w,i)=><p key={i} className="text-xs text-amber-200 mb-2">{w}</p>)}{report.results.map((r,i)=><div key={i} className="border-t border-slate-700 py-4"><div className="flex justify-between gap-4"><a className="text-teal-300 font-medium" href={r.url} target="_blank" rel="noreferrer">{r.title}{r.company&&' · '+r.company} ↗</a>{r.fitScore!==null&&<span className="text-teal-200 whitespace-nowrap">{r.fitScore}% fit</span>}</div><p className="text-slate-300 mt-2">{r.summary}</p>{r.resumeMatch&&<p className="text-sm text-slate-400 mt-2">{r.resumeMatch}</p>}{r.keyGaps.length>0&&<p className="text-sm mt-2">Gaps: {r.keyGaps.join(', ')}</p>}{r.missingKeywords.length>0&&<p className="text-sm mt-2">ATS keywords: {r.missingKeywords.join(', ')}</p>}</div>)}</article>)}</section>
 {saved.length>0&&<section className="mt-8"><h2 className="text-xl font-semibold">Saved in this browser</h2>{saved.map(r=><details className="panel mt-3" key={r.id}><summary>{r.tabTitle} · {new Date(r.created_at).toLocaleDateString()} · {r.results.length} results</summary><pre className="whitespace-pre-wrap text-xs mt-3">{JSON.stringify(r.results,null,2)}</pre></details>)}</section>}
 </main><nav aria-label="Search tabs" className="fixed bottom-0 inset-x-0 bg-slate-900 border-t border-slate-700 p-3 flex gap-2 overflow-x-auto">{tabs.map(t=><button disabled={busy} aria-current={t.code===active?'page':undefined} className={t.code===active?'active':''} key={t.code} onClick={()=>setActive(t.code)}>{t.config.title}</button>)}<button disabled={busy} onClick={()=>{setActive(undefined);setForm({...blank,companies:[],roles:[],skills:[],locations:[]});}}>+ New tab</button></nav>
 {prune&&<div className="fixed inset-0 bg-black/70 grid place-items-center p-6"><section role="dialog" aria-modal="true" aria-labelledby="prune-title" className="panel max-w-md"><h2 id="prune-title" className="text-xl">Delete older saved reports?</h2><p className="my-4 text-slate-300">This removes locally saved reports created 30 or more days ago. Backend reports remain available.</p><button onClick={()=>{const next=saved.filter(r=>new Date(r.created_at).getTime()>Date.now()-30*86400000);if(store(REPORT_KEY,next))setSaved(next);setPrune(false);}}>Delete older reports</button><button onClick={()=>setPrune(false)}>Cancel</button></section></div>}
 </div>;
}
createRoot(document.getElementById('root')).render(<BrowserRouter><Routes><Route path="*" element={<App/>}/></Routes></BrowserRouter>);
