import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,Routes,Route} from 'react-router-dom';
import {configSchema} from '../server/config.js';
import {backupSchema,emptyState,loadState,mergeBackup,recentHistory,pruneReports} from '../shared/history.js';
import {search} from './search.js';
import './style.css';
const blank=()=>({title:'New search',mode:'jobs',companies:[],roles:[],skills:[],locations:[],strictCompany:false,strictRole:false,strictSkills:false,resume:'',prompt:'',limit:10});
function App(){
 const [state,setState]=useState(emptyState),[active,setActive]=useState(),[form,setForm]=useState(blank),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[progress,setProgress]=useState(),[usage,setUsage]=useState(0),[prune,setPrune]=useState(false),[remove,setRemove]=useState(false),[unsaved,setUnsaved]=useState();
 const abort=useRef(),importFile=useRef();
 function updateUsage(){try{let bytes=0;for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);bytes+=(k.length+(localStorage.getItem(k)||'').length)*2;}setUsage(bytes);}catch{}}
 useEffect(()=>{try{const initial=loadState(localStorage);setState(initial);setActive(initial.tabs[0]?.id);setForm(initial.tabs[0]?.config||blank());}catch{setNotice('Saved browser data could not be read. Import a valid backup to recover your data.');}setReady(true);updateUsage();return()=>abort.current?.abort();},[]);
 function persist(next){try{const checked=backupSchema.parse(next);localStorage.setItem('djs.state',JSON.stringify(checked));try{localStorage.removeItem('djs.tabs');localStorage.removeItem('djs.reports');}catch{}setState(checked);updateUsage();return checked;}catch(e){setNotice(e.name==='ZodError'?'Data limits exceeded. Export a backup and remove older reports.':'Browser storage is full or unavailable. Export your data before removing older reports.');return null;}}
 function save(){const config=configSchema.parse({...form,...Object.fromEntries(['companies','roles','skills','locations'].map(k=>[k,form[k].filter(x=>x.trim())]))});const id=active||crypto.randomUUID();const next={...state,tabs:active?state.tabs.map(t=>t.id===id?{id,config}:t):[...state.tabs,{id,config}]};const saved=persist(next);if(!saved)throw new Error('Could not save search settings');setActive(id);return {id,config,saved};}
 function select(tab){setActive(tab?.id);setForm(tab?.config||blank());setProgress(undefined);setNotice('');setUnsaved(undefined);}
 function exportData(){const data=unsaved?{...state,reports:[...state.reports.filter(r=>r.id!==unsaved.id),unsaved]}:state;const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='daily-job-search-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function importData(file){if(!file)return;setBusy(true);try{if(file.size>5*1024*1024)throw new Error('Backup must be smaller than 5 MB');const next=mergeBackup(state,JSON.parse(await file.text()));if(persist(next)){if(!active)select(next.tabs[0]);setNotice('Backup imported. Existing records were kept; new records were added.');}}catch(e){setNotice(e.name==='ZodError'?'Invalid backup. Nothing was imported.':e.message);}finally{if(importFile.current)importFile.current.value='';setBusy(false);}}
 async function run(){setBusy(true);setNotice('');setProgress(undefined);setUnsaved(undefined);const controller=new AbortController();abort.current=controller;try{const {id,config,saved}=save();const report=await search({tabId:id,config,history:recentHistory(saved,id)},setProgress,controller.signal);if(persist({...saved,reports:[...saved.reports,report]}))setNotice('Report complete and saved in this browser.');else setUnsaved(report);}catch(e){setNotice(controller.signal.aborted?'Search cancelled. No report was saved.':e.issues?.map(i=>i.message).join('; ')||e.message);}finally{setBusy(false);setProgress(undefined);abort.current=undefined;}}
 const change=(key,value)=>setForm(f=>({...f,[key]:value}));
 function toggleApplied(job){const exists=state.applications.some(j=>j.url===job.url);persist({...state,applications:exists?state.applications.filter(j=>j.url!==job.url):[...state.applications,{...job,appliedAt:new Date().toISOString()}]});}
 const reports=[...state.reports.filter(r=>r.tabId===active),...(unsaved?[unsaved]:[])].sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt));
 return <div className="min-h-screen bg-slate-950 text-slate-100 pb-28"><header className="border-b border-slate-800"><div className="max-w-6xl mx-auto px-6 py-5 flex flex-wrap gap-4 items-center justify-between"><div><p className="text-teal-300 text-xs uppercase tracking-widest">Your next opportunity</p><h1 className="text-xl font-semibold">Daily Job Search Report</h1></div><div className="flex flex-wrap gap-2 items-center text-sm text-slate-400"><span>Browser storage: {(usage/1024).toFixed(1)} KB</span><button disabled={busy||!ready} onClick={exportData}>Export JSON</button><button disabled={busy||!ready} onClick={()=>importFile.current.click()}>Import JSON</button><input ref={importFile} className="hidden" type="file" accept="application/json,.json" aria-label="Import JSON backup" onChange={e=>importData(e.target.files[0])}/><button disabled={busy} onClick={()=>setPrune(true)}>Delete reports 30+ days old</button></div></div></header>
 <main className="max-w-6xl mx-auto p-6">{notice&&<p role="status" className="bg-amber-950 text-amber-100 p-4 rounded mb-5">{notice}</p>}
 {progress&&<div role="status" aria-live="polite" className="panel mb-5"><p className="text-teal-300">{progress.message}{progress.total?` (${progress.current}/${progress.total})`:''}</p><button onClick={()=>abort.current?.abort()}>Cancel search</button></div>}
 <section className="panel"><div className="flex justify-between flex-wrap gap-3"><div><h2 className="text-2xl font-semibold">Shape your search</h2><p className="text-slate-400 mt-1">Search when you’re ready. Your settings and reports stay in this browser.</p></div><button disabled={busy||!ready} onClick={run}>{busy?'Searching…':'Search now'}</button></div>
 <fieldset disabled={busy||!ready} className="mt-6"><div className="grid md:grid-cols-2 gap-5"><label>Tab title<input value={form.title} onChange={e=>change('title',e.target.value)}/></label><div><span className="label">Search mode</span><div className="flex gap-6 py-3">{['jobs','news'].map(mode=><label key={mode} className="flex gap-2 items-center"><input type="radio" name="mode" checked={form.mode===mode} onChange={()=>change('mode',mode)}/>{mode==='jobs'?'Jobs':'Tech news'}</label>)}</div></div></div>
 {form.mode==='jobs'?<><div className="grid md:grid-cols-2 gap-5 mt-5">{[['companies','Companies'],['roles','Job titles'],['skills','Key skills'],['locations','Locations']].map(([key,label])=><label key={key}>{label}<input value={form[key].join(',')} placeholder="Separate entries with commas" onChange={e=>change(key,e.target.value.split(',').map(x=>x.trim()))}/></label>)}</div><div className="flex flex-wrap gap-6 my-5">{[['strictCompany','Require a listed company'],['strictRole','Require a listed title'],['strictSkills','Require all listed skills']].map(([key,label])=><label key={key} className="flex gap-2 items-center"><input type="checkbox" checked={form[key]} onChange={e=>change(key,e.target.checked)}/>{label}</label>)}</div><label>Resume text<textarea rows="6" value={form.resume} onChange={e=>change('resume',e.target.value)} placeholder="Paste your resume for fit scores and ATS keyword suggestions"/></label><p className="text-xs text-slate-400 mt-2">Saved locally and sent through the backend to OpenAI when you search. Your JSON backup includes your resume.</p></>:<label className="block mt-5">News search prompt<textarea rows="4" value={form.prompt} onChange={e=>change('prompt',e.target.value)} placeholder="New technologies for software developers, or industry trends…"/></label>}
 <div className="flex flex-wrap gap-6 items-end mt-5"><label>Results to search (1–20)<input type="number" min="1" max="20" value={form.limit} onChange={e=>change('limit',Number(e.target.value))}/></label><button onClick={()=>{try{save();setNotice('Search settings saved locally.');}catch(e){setNotice(e.issues?.map(i=>i.message).join('; ')||e.message);}}}>Save settings</button>{active&&<button onClick={()=>setRemove(true)}>Delete tab</button>}</div><p className="text-xs text-slate-400 mt-3">Jobs shown in this tab or marked as applied within the last 30 days are excluded. Strict filters may return fewer results than requested.</p>
 </fieldset></section>
 <section className="mt-8"><h2 className="text-xl font-semibold mb-4">Your reports</h2>{!reports.length&&<div className="panel text-slate-400">Your report will appear here after you search.</div>}{reports.map(report=><article className="panel mb-4" key={report.id}><div className="mb-4"><h3 className="font-semibold">{new Date(report.createdAt).toLocaleString()}</h3><p className="text-sm text-slate-400">{report.results.length} results{report===unsaved?' · Not saved — export to keep it':''}</p></div>{report.warnings.map((w,i)=><p key={i} className="text-xs text-amber-200 mb-2">{w}</p>)}{report.results.map((r,i)=><div key={i} className="border-t border-slate-700 py-4"><div className="flex justify-between gap-4"><a className="text-teal-300 font-medium" href={r.url} target="_blank" rel="noreferrer">{r.title}{r.company&&' · '+r.company} ↗</a>{r.fitScore!==null&&<span className="text-teal-200 whitespace-nowrap">{r.fitScore}% fit</span>}</div><p className="text-slate-300 mt-2">{r.summary}</p>{r.resumeMatch&&<p className="text-sm text-slate-400 mt-2">{r.resumeMatch}</p>}{r.keyGaps.length>0&&<p className="text-sm mt-2">Gaps: {r.keyGaps.join(', ')}</p>}{r.missingKeywords.length>0&&<p className="text-sm mt-2">ATS keywords: {r.missingKeywords.join(', ')}</p>}{state.tabs.find(t=>t.id===report.tabId)?.config.mode!=='news'&&<button className="mt-3" disabled={busy} onClick={()=>toggleApplied(r)}>{state.applications.some(j=>j.url===r.url)?'Applied — undo':'Mark as applied'}</button>}</div>)}</article>)}</section>
 <section className="mt-8"><h2 className="text-xl font-semibold mb-4">Application history</h2>{!state.applications.length?<p className="text-slate-400">Use “Mark as applied” after submitting an application.</p>:state.applications.map(j=><div className="panel mb-3 flex justify-between flex-wrap gap-3" key={j.url}><div><a className="text-teal-300" href={j.url} target="_blank" rel="noreferrer">{j.title} · {j.company}</a><p className="text-sm text-slate-400">Applied {new Date(j.appliedAt).toLocaleDateString()}</p></div><button disabled={busy} onClick={()=>toggleApplied(j)}>Undo applied</button></div>)}</section>
 </main><nav aria-label="Search tabs" className="fixed bottom-0 inset-x-0 bg-slate-900 border-t border-slate-700 p-3 flex gap-2 overflow-x-auto">{state.tabs.map(t=><button disabled={busy} aria-current={t.id===active?'page':undefined} className={t.id===active?'active':''} key={t.id} onClick={()=>select(t)}>{t.config.title}</button>)}<button disabled={busy||!ready} onClick={()=>select()}>+ New tab</button></nav>
 {(prune||remove)&&<div className="fixed inset-0 bg-black/70 grid place-items-center p-6"><section role="dialog" aria-modal="true" aria-labelledby="dialog-title" className="panel max-w-md"><h2 id="dialog-title" className="text-xl">{prune?'Delete older saved reports?':'Delete this tab and its reports?'}</h2><p className="my-4 text-slate-300">{prune?'Remove reports created 30 or more days ago. Application history and tabs are kept.':'This removes the tab and its reports from this browser. Application history is kept.'}</p><button onClick={()=>{if(prune){persist(pruneReports(state));setPrune(false);}else{const next={...state,tabs:state.tabs.filter(t=>t.id!==active),reports:state.reports.filter(r=>r.tabId!==active)};if(persist(next))select(next.tabs[0]);setRemove(false);}}}>Delete</button><button onClick={()=>{setPrune(false);setRemove(false);}}>Cancel</button></section></div>}
 </div>;
}
createRoot(document.getElementById('root')).render(<BrowserRouter><Routes><Route path="*" element={<App/>}/></Routes></BrowserRouter>);
