import {test} from 'node:test';
import assert from 'node:assert/strict';
import {providers} from '../server/providers.js';
import {configSchema} from '../server/config.js';
const c=configSchema.parse({title:'Jobs',roles:['Engineer'],limit:20,resume:'PRIVATE'});
function env(t,values){const previous={};for(const [key,value] of Object.entries(values)){previous[key]=process.env[key];if(value===undefined)delete process.env[key];else process.env[key]=value;}t.after(()=>{for(const [key,value] of Object.entries(previous)){if(value===undefined)delete process.env[key];else process.env[key]=value;}});}
function response(data){return {ok:true,json:async()=>data};}
test('SerpApi defaults, paginates to 20 and does not send resume',async t=>{
 env(t,{SERPAPI_API_KEY:'test',SEARCH_PROVIDER:undefined});const calls=[];
 t.mock.method(global,'fetch',async u=>{calls.push(u);return response({search_metadata:{status:'Success'},organic_results:Array.from({length:10},(_,i)=>({title:'Job',link:`https://example.com/${calls.length}/${i}`,snippet:'Job'})),serpapi_pagination:{next:'https://not-followed.example.com'}});});
 const results=await providers.search(c);assert.equal(results.length,20);assert.deepEqual(results[0],{title:'Job',url:'https://example.com/1/0',snippet:'Job'});assert.equal(calls.length,2);assert.deepEqual(calls.map(u=>u.searchParams.get('start')),['0','10']);assert.ok(calls.every(u=>u.origin==='https://serpapi.com'&&u.searchParams.get('engine')==='google'&&u.searchParams.get('api_key')==='test'&&!u.searchParams.has('num')&&!u.toString().includes('PRIVATE')));
});
test('SerpApi caps small requests and supplies empty snippet fallback',async t=>{env(t,{SERPAPI_API_KEY:'test',SEARCH_PROVIDER:'serpapi'});let calls=0;t.mock.method(global,'fetch',async()=>{calls++;return response({organic_results:Array.from({length:10},(_,i)=>({title:'Job',link:`https://example.com/${i}`})),serpapi_pagination:{next:'next'}});});const results=await providers.search({...c,limit:3});assert.equal(results.length,3);assert.equal(results[0].snippet,'');assert.equal(calls,1);});
test('SerpApi stops without a next page, including successful empty results',async t=>{env(t,{SERPAPI_API_KEY:'test',SEARCH_PROVIDER:'serpapi'});let calls=0;t.mock.method(global,'fetch',async()=>{calls++;return response({search_metadata:{status:'Success'},organic_results:[]});});assert.deepEqual(await providers.search(c),[]);assert.equal(calls,1);});
test('SerpApi JSON errors and HTTP errors fail the run',async t=>{env(t,{SERPAPI_API_KEY:'test',SEARCH_PROVIDER:'serpapi'});const fetch=t.mock.method(global,'fetch',async()=>response({error:'private provider details',search_metadata:{status:'Error'}}));await assert.rejects(providers.search(c),/SerpApi search failed/);fetch.mock.mockImplementation(async()=>({ok:false,status:429}));await assert.rejects(providers.search(c),/HTTP 429/);});
test('SerpApi credentials are required and removed Google option is rejected',async t=>{env(t,{SERPAPI_API_KEY:undefined,SEARCH_PROVIDER:undefined});await assert.rejects(providers.search(c),/Missing SERPAPI_API_KEY/);process.env.SEARCH_PROVIDER='google';await assert.rejects(providers.search(c),/serpapi or firecrawl/);});
test('news prompts use SerpApi without resume or job-board filters',async t=>{env(t,{SERPAPI_API_KEY:'test',SEARCH_PROVIDER:'serpapi'});t.mock.method(global,'fetch',async u=>{assert.equal(u.searchParams.get('q'),'New developer technologies');assert.ok(!u.toString().includes('PRIVATE'));return response({organic_results:[]});});await providers.search({...c,mode:'news',prompt:'New developer technologies'});});
test('Firecrawl search maps v2 web results',async t=>{env(t,{SEARCH_PROVIDER:'firecrawl',FIRECRAWL_API_KEY:'test'});t.mock.method(global,'fetch',async(url,options)=>{assert.equal(JSON.parse(options.body).limit,20);return response({success:true,data:{web:[{title:'Job',url:'https://example.com',description:'Engineer'}]}});});assert.deepEqual(await providers.search(c),[{title:'Job',url:'https://example.com',snippet:'Engineer'}]);});
test('structured evaluations reject invalid scores',async t=>{env(t,{OPENAI_API_KEY:'test'});t.mock.method(global,'fetch',async(url,options)=>{const body=JSON.parse(options.body);assert.equal(body.response_format.type,'json_schema');return response({choices:[{message:{content:JSON.stringify({title:'Engineer',company:'Acme',summary:'Job',fitScore:200,keyGaps:[],missingKeywords:[],resumeMatch:'Match'})}}]});});await assert.rejects(providers.evaluate(c,{title:'Job'},'text'));});
