import {test} from 'node:test';
import assert from 'node:assert/strict';
import {makeRunner,runScheduled} from '../server/runner.js';
import {configSchema,queryFor} from '../server/config.js';
import {createApp} from '../server/app.js';
const code='159f4603-eaee-47c4-bd9a-a43308e80545';
const config=configSchema.parse({title:'Engineer',roles:['Engineer'],companies:['Acme'],limit:20});
function fixture(){const state={results:[],sources:[],recent:[],locked:false};const store={get:async()=>config,locked:async(c,fn)=>{if(state.locked){const e=new Error('A search is already running');e.status=409;throw e;}state.locked=true;try{return await fn();}finally{state.locked=false;}},enabled:async()=>[code],recent:async()=>state.recent,start:async(id,c,source)=>state.sources.push(source),finish:async(id,r,w)=>{state.results=r;state.warnings=w;},fail:async()=>state.failed=true};const providers={search:async()=>[{url:'https://example.com/job',title:'Engineer',snippet:'Acme Engineer TypeScript'}],scrape:async()=>null,evaluate:async()=>({title:'Engineer',company:'Acme',summary:'Build software',fitScore:80,keyGaps:[],missingKeywords:[],resumeMatch:'Good'})};return {state,store,providers,run:()=>makeRunner(store,providers)};}
test('manual HTTP request and cron invoke the same pipeline and persist source',async()=>{const f=fixture(),run=f.run(),server=createApp(f.store,run).listen(0);await new Promise(r=>server.once('listening',r));try{const response=await fetch(`http://localhost:${server.address().port}/api/searches/${code}/run`,{method:'POST'});assert.equal(response.status,200);assert.equal((await response.json()).results.length,1);await runScheduled(f.store,run);assert.deepEqual(f.state.sources,['manual','cron']);}finally{await new Promise(r=>server.close(r));}});
test('30-day title/company and URL deduplication',async()=>{const f=fixture();f.state.recent=[{title:'ENGINEER',company:'Acme',url:'https://other.com/job'}];await f.run()(code);assert.equal(f.state.results.length,0);f.state.recent=[{title:'Other',company:'Other',url:'https://example.com/job'}];await f.run()(code);assert.equal(f.state.results.length,0);});
test('strict skill matching filters nonmatches',async()=>{const f=fixture();f.store.get=async()=>({...config,skills:['Rust'],strictSkills:true});await f.run()(code);assert.equal(f.state.results.length,0);});
test('scrape failures fall back to snippets with warning',async()=>{const f=fixture();f.providers.scrape=async()=>{throw new Error('blocked');};await f.run()(code);assert.equal(f.state.results.length,1);assert.equal(f.state.warnings.length,1);});
test('provider failure persists a failed report and releases the lock',async()=>{const f=fixture();f.providers.search=async()=>{throw new Error('offline');};await assert.rejects(f.run()(code),/offline/);assert.equal(f.state.failed,true);assert.equal(f.state.locked,false);});
test('overlapping calls reject without duplicate execution',async()=>{const f=fixture();let release;f.providers.search=()=>new Promise(r=>release=r);const run=f.run(),first=run(code);while(!release)await new Promise(r=>setImmediate(r));await assert.rejects(run(code),e=>e.status===409);release([]);await first;assert.equal(f.state.sources.length,1);});
test('configuration caps results, requires news prompt, and builds search without resume',()=>{assert.equal(configSchema.safeParse({...config,limit:21}).success,false);assert.equal(configSchema.safeParse({...config,mode:'news'}).success,false);assert.ok(!queryFor({...config,resume:'PRIVATE RESUME'}).includes('PRIVATE'));});
test('news deduplicates URLs rather than company/title',async()=>{const f=fixture();f.store.get=async()=>({...config,mode:'news'});f.state.recent=[{title:'Engineer',company:'Acme',url:'https://other.com'}];await f.run()(code);assert.equal(f.state.results.length,1);});
test('codes are normalized before locking and invalid codes are rejected',async()=>{const f=fixture();let received;const app=createApp(f.store,async(c)=>{received=c;return {};});const server=app.listen(0);await new Promise(r=>server.once('listening',r));try{const root=`http://localhost:${server.address().port}`;assert.equal((await fetch(`${root}/api/searches/${code.toUpperCase()}/run`,{method:'POST'})).status,200);assert.equal(received,code);assert.equal((await fetch(`${root}/api/searches/invalid/run`,{method:'POST'})).status,400);}finally{await new Promise(r=>server.close(r));}});
